# entrypoint: python run.py
# env: flex
# runtime: python


runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: .*
  script: views.app

# libraries:
# - name: webapp2
#   version: "2.5.2"
